plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		url 'https://maven.wispforest.io/releases/'
	}
	maven {
		name = "Jared's maven"
		url = "https://maven.blamejared.com/"
	}
	maven {
		name = "ModMaven"
		url = "https://modmaven.dev"
	}
	maven { url 'https://jitpack.io' }
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"moreoverlays" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

sourceSets {
	main {
		resources {
			srcDir 'src/client/resources'
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"

	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation "io.wispforest:owo-lib:${project.owo_version}"
	include "io.wispforest:owo-sentinel:${project.owo_version}"

	compileOnlyApi("mezz.jei:jei-26.1.2-common-api:${project.jei_version}")
	compileOnlyApi("mezz.jei:jei-26.1.2-fabric-api:${project.jei_version}")
	runtimeOnly("mezz.jei:jei-26.1.2-fabric:${project.jei_version}")

	// implementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_api_version}"
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_version", project.minecraft_version

	filesMatching("fabric.mod.json") {
		expand([
			"version"           : inputs.properties.version,
			"minecraft_version" : inputs.properties.minecraft_version,
		])
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "projectName", project.name

	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}" }
	}
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('jar') {
	archiveVersion.set("${project.version}-mc${project.minecraft_version}-fabric")
}

tasks.named('sourcesJar') {
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	archiveVersion.set("${project.version}-mc${project.minecraft_version}-fabric")
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
