# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4

# Fabric API
fabric_version=0.141.2+1.21.11

# Mod Properties
mod_version=1.24.1
maven_group=at.ridgo8.moreoverlays
archives_base_name=moreoverlays

# OWO lib
owo_version=0.13.0+1.21.11

